spring.application.name : Messenger
server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: course 
    redis:
      host: localhost
      port: 6379
      database: 0
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtp
    username: al.5alimov@yandex.ru
    password: hqwhhvatptdjhjfk
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  logging:
    level:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE