spring.application.name : Messenger
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  logging:
    level:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE